image: 1science/sbt

stages:
  - test

before_script:
  - sbt sbt-version


test:
  stage: test
  artifacts:
      paths:
        - target/scala-2.11/term-rewriting-assembly-1.0.jar
  script:
    - sbt clean assembly
