image: java:8

stages:
  - test

before_script:
  - apt-get update -y
  - apt-get install apt-transport-https -y
  ## Install SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  - apt-get update -y
  - apt-get install sbt -y
  - sbt sbt-version


test:
  stage: test
  artifacts:
      paths:
        - target/scala-2.11/term-rewriting-assembly-1.0.jar
  script:
    - sbt clean assembly
